server:
  port: 8090
spring:
  application:
    name: FastFood-API
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.168.154:8848
    gateway:
      routes:
        - id: ProductCenter
          uri: lb://Product-Center
          predicates:
            - Path=/detailType/**,/product/**,/type/**,/productDetail/**
        - id: StoreCenter
          uri: lb://Store-Center
          predicates:
            - Path=/store/**


management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
logging:
  level:
    com.wang.fastfoodapi: debug

token:
  # 1000 * 60 * 60 * 24 * 3 \u4E09\u5929
  expireTime: 259200000
  secretKey: abcdefghijklmnopqrstuvwxyz
  # JWT 负载中拿到开头
  tokenHead: Bearer
  # JWT存储的请求头
  tokenHeader: authorization

