server:
  port: 8090
spring:
  application:
    name: FastFood-API
  cloud:
    nacos:
      server-addr: 121.196.168.154:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
logging:
  level:
    com.wang.fastfoodapi: debug

